site_name: Entropiq Client Documentation
site_description: Install, configured and maintain the EntropiQ clients
copyright: Copyright 2026 EntropiQ Corp
theme:
  name: readthedocs

nav:
  - Overview: index.md
  - Install: install.md
  - Advanced: advanced.md
  - How It Works: architecture.md
  - Troubleshooting: troubleshooting.md
  - Reference: reference.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
